### ISSUE TITLE
Is this repo still active?

### ISSUE THREAD

**Issue by imjasonh** [googlearchive/titan#3]
There have been no code commits for 7 years, and some of the features supported by the library aren't supported by the platform anymore (e.g., Channel API).

If this isn't supported it could be useful to mark it as such to avoid disappointment if people stumble across it.

**Comment by tswast** [comment]
@ace-n this repo might be a good candidate to archive

**Comment by ace-n** [comment]
@engelke (GAE DPE lead) LGTM'd, so I'm archiving this repo.
